# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895b97b4c328d38368d03639e3227468b333f263a415f07088656b0dd525e57cbcf2ac22ea4ed2e682341e0964c2e29ed3a52246336603ad6d96797a5b032f10

test:
  secret_key_base: f0861cb080bcbf433d1d95edb29ea2ed047d725ebb0cd37a272339392af5da267c2cf628c1f9677b9e4133ae352753aa519f1f2b4c38eb15f6f0841b41043edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
